import turtle
import math
turtle.speed(10)
turtle.color("yellow")
turtle.begin_fill()
turtle.circle(150)
turtle.end_fill()

turtle.color("blue")
turtle.penup()
turtle.setpos(-70, 180)
turtle.pendown()
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.penup()
turtle.setpos(70, 180)
turtle.pendown()
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.penup()
turtle.setpos(0, 150)
turtle.pendown()
turtle.right(90)

turtle.color("black")
turtle.width(10)

turtle.forward(60)
turtle.penup()
turtle.setpos(0, 40)
turtle.pendown()
turtle.left(90)

turtle.color("red")
turtle.circle(110, 30)
turtle.penup()
turtle.setpos(0, 40)
turtle.pendown()
turtle.setheading(180)
turtle.circle(-110, 30)
